name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Prepare release
        id: bump
        run: python3 tool/bump_version.py

      - name: Commit release artifacts
        if: steps.bump.outputs.skip != 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml CHANGELOG.md
          git commit -m "chore(release): v${{ steps.bump.outputs.version }}"

      - name: Rebase onto latest main
        if: steps.bump.outputs.skip != 'true'
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Create tag
        if: steps.bump.outputs.skip != 'true'
        run: |
          git tag -a v${{ steps.bump.outputs.version }} -m "v${{ steps.bump.outputs.version }}"

      - name: Push changes
        if: steps.bump.outputs.skip != 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD
          git push origin v${{ steps.bump.outputs.version }}

      - name: Publish GitHub release
        if: steps.bump.outputs.skip != 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.bump.outputs.version }}
          name: v${{ steps.bump.outputs.version }}
          body: ${{ steps.bump.outputs.release_notes }}
